---
title: "Wordcloud"
author: "Jake Daniels"
date: "August 16, 2018"
output: html_document
---
```{r warning=FALSE}
#install.packages("wordcloud2")
library(wordcloud2)
library(rtweet)
library(tidyverse)
library(tidytext) 
```

```{r}
#insert your own tokens
create_token(app = Sys.getenv("TWITTER_APP"),
  consumer_key = Sys.getenv("TWITTER_CONSUMER_KEY"),
  consumer_secret = Sys.getenv("TWITTER_CONSUMER_SECRET"))
```
Token Scrape
```{r}
data(stop_words)
# get the tweets
rtr <- search_tweets("#RoadToRyerson", n = 2000, include_rts = FALSE)

rtrTable <- rtr %>%
  unnest_tokens(word, text) %>%  #Unnest the words - code via Tidy Text
  anti_join(stop_words) %>%  #remove stop words
  count(word, sort = T) %>% #do a word count
  filter(!word %in% c('t.co', 'https', 'roadtoryerson', 'amp', 'ryersonu', 'ryerson', 'ryersonsa', 'ryersonfcs', 'student', 1:10))
rtrTable
```

WordCloud
```{r}
ryePallete <- c('#1C5F9B', '#C1138A', '#2E1D3B', '#FCC210')

wordcloud2(rtrTable, size=0.7, color=rep_len( ryePallete, nrow(rtrTable)))
```